version: '3.9'
services:
  autotests:
    container_name: autotests
    build:
      context: .
      dockerfile: Dockerfile-autotests
    volumes:
      - ./allure-results/:/home/tests/allure-results
    networks:
      - api

  mockserver:
    container_name: mockserver
    build:
      context: .
      dockerfile: Dockerfile-wiremock
    ports:
      - 8081:8081
    volumes:
      - ./mocks/:/mocks
    command: |
      --global-response-templating
      --verbose 
      --port 8081
      --root-dir /mocks
      --proxy-all https://reqres.in
    networks:
      - api

networks:
  api:
    name: api